#
# SHV - Small HyperVisor for testing nested virtualization in hypervisors
# Copyright (C) 2023  Eric Li
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1

jobs:
  test-shv:
    machine:
      # Need nested virtualization
      # https://discuss.circleci.com/t/new-android-machine-image-now-/39467
      image: android:2022.03.1
    resource_class: medium
    parameters:
      subarch:
        type: string
    steps:
      - checkout
      - run:
          name: "Apt-get"
          command: |
            sudo apt-get update
            sudo apt-get -y -q install \
                build-essential crossbuild-essential-i386 \
                autoconf libtool xorriso mtools grub-pc \
                git qemu-system-x86
      - run:
          name: "Build"
          command: |
            tools/build.sh --<< parameters.subarch >> -O0 --shv-opt 0xdfd
      - run:
          name: "Versions"
          command: |
            lscpu
            ssh -V
            qemu-system-x86_64 -version
            gcc -v
      - store_artifacts:
          path: shv.bin
      - store_artifacts:
          path: grub.iso
      - run:
          name: "Test"
          command: |
            rm -rf tmp
            mkdir tmp
            python3 -u ./tools/ci/test5.py \
                --shv-img ${PWD}/shv.bin \
                --work-dir ${PWD}/tmp/ \
                --no-display \
                --verbose \
                --watch-serial
  test-nmi:
    machine:
      # Need nested virtualization
      # https://discuss.circleci.com/t/new-android-machine-image-now-/39467
      image: android:2022.03.1
    resource_class: medium
    parameters:
      subarch:
        type: string
    steps:
      - checkout
      - run:
          name: "Apt-get"
          command: |
            sudo apt-get update
            sudo apt-get -y -q install \
                build-essential crossbuild-essential-i386 \
                autoconf libtool xorriso mtools grub-pc \
                git qemu-system-x86
      - run:
          name: "Build"
          command: |
            tools/build.sh --<< parameters.subarch >> -O0 --nmi-opt 0x1
      - run:
          name: "Versions"
          command: |
            set -xe
            lscpu
            ssh -V
            qemu-system-x86_64 -version
            uname -r
            gcc -v
      - store_artifacts:
          path: shv.bin
      - store_artifacts:
          path: grub.iso
      - run:
          name: "Test"
          command: |
            rm -rf tmp
            mkdir tmp
            python3 -u ./tools/ci/test5.py \
                --shv-img ${PWD}/shv.bin \
                --work-dir ${PWD}/tmp/ \
                --no-display \
                --verbose \
                --watch-serial \
                --qemu-timeout 60 \
                --nmi

workflows:
  test-shv-workflow:
    jobs:
      - test-shv:
          matrix:
            parameters:
              subarch: ["i386", "pae", "amd64"]
      - test-nmi:
          matrix:
            parameters:
              subarch: ["i386", "amd64"]
