/*
 * SHV - Small HyperVisor for testing nested virtualization in hypervisors
 * Copyright (C) 2023  Eric Li
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * CI for testing SHV
 */

properties([
    parameters([
        string(name: 'SHV_BRANCH', defaultValue: 'master'),
        string(name: 'BUILD_OPTS', defaultValue: ''),
        string(name: 'TEST_SHV_OPT', defaultValue: 'shv_opt=0xdfd'),
        string(name: 'TEST_NMI_OPT', defaultValue: 'nmi_opt=0x1f nmi_exp=0')
    ])
])

void qemu_test(String work_dir, String append, String args) {
    PWD = sh(returnStdout: true, script: 'pwd').trim()
    sh "rm -rf ${work_dir}"
    sh "mkdir ${work_dir}"
    sh """
        python3 -u ./tools/ci/test5.py \
            --shv-img ${PWD}/shv.bin \
            --mb-cmdline "${append}" \
            --work-dir ${PWD}/tmp/ \
            --no-display \
            --verbose \
            --watch-serial \
            ${args}
    """
}

def helper

pipeline {
    agent any

    stages {
        stage('Logistics') {
            steps {
                sh "git fetch origin ${params.SHV_BRANCH}"
                sh "git checkout ${params.SHV_BRANCH}"
                sh "git pull origin ${params.SHV_BRANCH}"
                script {
                    cmt = sh(
                        returnStdout: true,
                        script: 'git rev-parse HEAD | head -c 9').trim()
                    currentBuild.displayName += " ${params.SHV_BRANCH}"
                    currentBuild.displayName += " ${cmt}"
                    helper = load "tools/ci/jenkins.groovy"
                }
            }
        }
        stage('Build i386') {
            steps {
                script {
                    helper.build_shv("i386", "${params.BUILD_OPTS}")
                }
            }
        }
        stage('Test i386') {
            parallel {
                stage('Test i386 SHV') {
                    steps {
                        qemu_test "tmp_i386_shv", "${TEST_SHV_OPT}", ""
                    }
                }
                stage('Test i386 NMI') {
                    steps {
                        qemu_test "tmp_i386_nmi", "${TEST_NMI_OPT}", "--nmi"
                    }
                }
            }
        }
        stage('Build pae') {
            steps {
                script {
                    helper.build_shv("pae", "${params.BUILD_OPTS}")
                }
            }
        }
        stage('Test pae') {
            parallel {
                stage('Test pae SHV') {
                    steps {
                        qemu_test "tmp_pae_shv", "${TEST_SHV_OPT}", ""
                    }
                }
                stage('Test pae NMI') {
                    steps {
                        qemu_test "tmp_pae_nmi", "${TEST_NMI_OPT}", "--nmi"
                    }
                }
            }
        }
        stage('Build amd64') {
            steps {
                script {
                    helper.build_shv("amd64", "${params.BUILD_OPTS}")
                }
            }
        }
        stage('Test amd64') {
            parallel {
                stage('Test amd64 SHV') {
                    steps {
                        qemu_test "tmp_amd64_shv", "${TEST_SHV_OPT}", ""
                    }
                }
                stage('Test amd64 NMI') {
                    steps {
                        qemu_test "tmp_amd64_nmi", "${TEST_NMI_OPT}", "--nmi"
                    }
                }
            }
        }
    }
}

