name: Build SHV

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch:
          - 'i386'
          - 'pae'
          - 'x86_64'
        optimize_mode:
          - 'O0'
          - 'O2'
          - 'O3'

    steps:
    - uses: actions/checkout@v3
    - name: apt-get
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
                     build-essential crossbuild-essential-i386 \
                     autoconf libtool xorriso mtools grub-pc
    - name: Build
      run: |
        tools/ci/build.sh --${{ matrix.target_arch }} \
                          -${{ matrix.optimize_mode }} \
                          --shv-opt 0xdfd
        make -j $(nproc)
    - name: Release
      uses: actions/upload-artifact@v3
      with:
        name: boot-${{ matrix.target_arch }}-${{ matrix.optimize_mode }}
        path: |
          shv.bin
          grub.iso

