name: Build XMHF with TrustVisor

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch:
          - 'i386'
#          - 'amd64'
#        optimize_mode:
#          - 'O0'
#          - 'O3'

    steps:
    - uses: actions/checkout@v3
    - name: apt-get
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
                     build-essential crossbuild-essential-i386 \
                     autoconf libtool xorriso mtools grub-pc
    - name: Build
      run: |
        autoreconf --install && \
        ./configure --host=i686-linux-gnu && \
        make -j $(nproc)
    - name: Release
      uses: actions/upload-artifact@v3
      with:
        name: boot-${{ matrix.target_arch }}
        #name: boot-${{ matrix.target_arch }}-${{ matrix.optimize_mode }}
        path: |
          shv.bin
          grub.iso

