name: Build XMHF with TrustVisor

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_arch:
          - 'x86'
          - 'x86_64'

    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: |
        sudo apt-get update && \
        sudo apt-get install \
                      openssh-server tmux vim git aptitude \
                      pbuilder texinfo ruby build-essential autoconf libtool \
                      crossbuild-essential-i386 \
                      -y
    - name: nproc
      run: |
        nproc
    - name: Build x86
      if: ${{ matrix.target_arch == 'x86' }}
      run: |
        ./autogen.sh
        ./configure \
          --with-approot=hypapps/trustvisor \
          --disable-drt \
          --enable-debug-symbols \
          CC=i686-linux-gnu-gcc \
          LD=i686-linux-gnu-ld
        make -j 4
    - name: Build x64
      if: ${{ matrix.target_arch == 'x86_64' }}
      run: |
        ./autogen.sh
        ./configure \
          --with-approot=hypapps/trustvisor \
          --disable-drt \
          --with-target-hwplatform=x86_64 \
          --enable-debug-symbols
        make -j 4
    - name: Release
      uses: actions/upload-artifact@v2
      with:
        name: boot-${{ matrix.target_arch }}
        path: |
          hypervisor-${{ matrix.target_arch }}.bin.gz
          init-${{ matrix.target_arch }}.bin

