name: Check indent (any in last 10 commits)

on: ["push", "pull_request"]

jobs:
  indent:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check indent
      run: |
        tools/ci/check_indent.sh

