name: Check indent (any in last 10 commits)

on: ["push", "pull_request"]

jobs:
  vmcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check VMCS macros
      run: |
        python3 tools/ci/check_indent.sh

